volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:14.10
    env_file:
      - .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "9000"
    restart: unless-stopped

  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/share/nginx/html/staticfiles
      - media_volume:/usr/share/nginx/html/media
    depends_on:
      - backend
    restart: unless-stopped