# Generated by Django 5.2.1 on 2025-05-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_delivery_departure_time_delivery_distance_km_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='address',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='media_file',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='technical_condition',
        ),
    ]
