# Generated by Django 5.2.1 on 2025-05-13 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_remove_delivery_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargotype',
            options={'verbose_name': 'Тип груза', 'verbose_name_plural': 'Типы груза'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Доставка', 'verbose_name_plural': 'Доставки'},
        ),
        migrations.AlterModelOptions(
            name='deliveryservice',
            options={'verbose_name': 'Услуга доставки', 'verbose_name_plural': 'Услуги доставки'},
        ),
        migrations.AlterModelOptions(
            name='deliverystatus',
            options={'verbose_name': 'Статус доставки', 'verbose_name_plural': 'Статусы доставки'},
        ),
        migrations.AlterModelOptions(
            name='packagingtype',
            options={'verbose_name': 'Тип упаковки', 'verbose_name_plural': 'Типы упаковки'},
        ),
        migrations.AlterModelOptions(
            name='transportmodel',
            options={'verbose_name': 'Транспортная модель', 'verbose_name_plural': 'Транспортные модели'},
        ),
        migrations.AlterField(
            model_name='delivery',
            name='cargo_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveries.cargotype', verbose_name='Тип груза'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateField(verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Расстояние (км)'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='packaging',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveries.packagingtype', verbose_name='Упаковка'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveries.deliveryservice', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveries.deliverystatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='transport_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveries.transportmodel', verbose_name='Модель транспорта'),
        ),
    ]
